services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=boom
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
#    expose:
#      - 5432
    ports:
      - "5432:5432"



  webapp:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:boom@db/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - "/app"

volumes:
  postgres_data:
